### ISSUE TITLE
Hi there!

### ISSUE THREAD

**Issue by unKILLableBRIAR** [UnsaltyPotatochip/DataStructureLearn#1]
Hello

**Comment by UnsaltyPotatochip** [comment]
Thank you for solving memory leak problem about https://github.com/UnsaltyPotatochip/DataStructureLearn/blob/main/Utilizes/Locker.c

**Comment by UnsaltyPotatochip** [comment]
If there is any modify to my code, leave more issue and comment like this :)
Thanks!
